apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: user-onboarding
    app.kubernetes.io/component: serverless-workflow
    app.kubernetes.io/managed-by: sonataflow-operator
    app.kubernetes.io/name: user-onboarding
    sonataflow.org/workflow-app: user-onboarding
    sonataflow.org/workflow-namespace: ""
  name: user-onboarding-secrets
stringData:
  BACKSTAGE_NOTIFICATIONS_URL: http://backstage-backstage.rhdh-operator
  NOTIFICATIONS_BEARER_TOKEN: ""
  ONBOARDING_SERVER_URL: http://user-onboarding-server.sonataflow-infra:8080
