apiVersion: v1
data:
  fail-switch.sw.input-schema.json: |
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "switch": {
          "title": "switch",
          "description": "Type of output for the workflow",
          "type": "string",
          "enum": ["OK", "KO", "Wait"],
          "default": "OK"
        }
      }
    }
  workflow-output-schema.json: |-
    {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "WorkflowResult",
        "description": "Schema of workflow output",
        "type": "object",
        "properties": {
            "result": {
                "$ref": "../shared/schemas/workflow-result-schema.json",
                "type": "object"
            }
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: 01-failswitch-resources-schemas
