apiVersion: v1
kind: Secret
metadata:
  name: greeting-auth-creds
  namespace: rhdh-operator
  labels:
    app: greeting-auth
    app.kubernetes.io/component: serverless-workflow
    app.kubernetes.io/managed-by: sonataflow-operator
    app.kubernetes.io/name: greeting-auth
    sonataflow.org/workflow-app: greeting-auth
type: Opaque
stringData:
  KEYCLOAK_AUTH_SERVER_URL: "https://keycloak-rhsso-operator.apps.ocp-test.qe.lab.redhat.com/auth/realms/basic"
  KEYCLOAK_CLIENT_ID: "rhdh"
  KEYCLOAK_CLIENT_SECRET: "rhdh"
